export const QUERY_KEYS = {
  BANK: {
    ALL_BANKS: "GET_ALL_BANKS",
    CREATE_USER_BANK_ACCOUNT: "CREATE_USER_BANK_ACCOUNT",
    PLATFORM_BANK_DETAILS: "GET_PLATFORM_BANK_DETAILS",
    UPDATE_DEFAULT_BANK_ACCOUNT: "UPDATE_DEFAULT_BANK_ACCOUNT",
    USER_BANK_ACCOUNTS: "GET_USER_BANK_ACCOUNTS",
  },
  CRYPTO: {
    SUPPORTED_CRYPTO: "GET_SUPPORTED_CRYPTO",
    PLATFORM_CRYPTO_WALLET: "GET_PLATFORM_CRYPTO_WALLET",
    GET_SUPPORTED_CRYPTO_BY_ID: "GET_SUPPORTED_CRYPTO_BY_ID",
    GET_CUSTODIAL_WALLETS: "GET_CUSTODIAL_WALLETS",
    GENERATE_CUSTODIAL_WALLET: "GENERATE_CUSTODIAL_WALLET",
    GENERATE_ALL_CUSTODIAL_WALLETS: "GENERATE_ALL_CUSTODIAL_WALLETS",
  },
  CURRENCY: {
    SUPPORTED_CURRENCY: "GET_SUPPORTED_CURRENCY",
  },
  DISPUTE: {
    GET_DISPUTE_DETAILS: "GET_DISPUTE_DETAILS",
    GET_DISPUTE_MESSAGES: "GET_DISPUTE_MESSAGES",
    INITIATE_DISPUTE_TRANSACTION: "INITIATE_DISPUTE_TRANSACTION",
    USER_SEND_DISPUTE_MESSAGE: "USER_SEND_DISPUTE_MESSAGE",
  },
  EXCHANGE_RATE: {
    GET_CRYPTO_TO_CURRENCY_EXCHANGE_RATE:
      "GET_CRYPTO_TO_CURRENCY_EXCHANGE_RATE",
  },
  TRANSACTION: {
    GET_AMOUNT_TO_SEND: "GET_AMOUNT_TO_SEND",
    INITIATE_TRANSACTION: "INITIATE_TRANSACTION",
    MAKE_PAYMENT_TRANSACTION: "MAKE_PAYMENT_TRANSACTION",
    CONFIRM_RECEIVING_PAYMENT_ACCOUNT: "CONFIRM_RECEIVING_PAYMENT_ACCOUNT",
    CREATE_AND_SUBMIT_TRANSACTION: "CREATE_AND_SUBMIT_TRANSACTION",
    USER_SEARCH_TRANSACTION_HISTORY: "USER_SEARCH_TRANSACTION_HISTORY",
    USER_TRANSACTION_SUMMARY: "USER_TRANSACTION_SUMMARY",
    USER_TRANSACTION_DETAILS: "USER_TRANSACTION_DETAILS",
    USER_INCOMPLETE_TRANSACTIONS_COUNT: "USER_INCOMPLETE_TRANSACTIONS_COUNT",
  },
  USER: {
    GET_PROFILE: "GET_PROFILE",
    PING: "PING_USER",
    REQUEST_PASSWORD_UPDATE: "REQUEST_PASSWORD_UPDATE",
    UPLOAD_PROFILE_PICTURE: "UPLOAD_PROFILE_PICTURE",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    REMOVE_PROFILE_PICTURE: "REMOVE_PROFILE_PICTURE",
  },
  TESTIMONIAL: {
    GET_PUBLISHED_TESTIMONIALS: "GET_PUBLISHED_TESTIMONIALS",
  },
  KYC: {
    GET_SESSION: "KYC_GET_SESSION",
    GET_STATUS: "KYC_GET_STATUS",
    START_SESSION: "KYC_START_SESSION",
    SELECT_ID_TYPE: "KYC_SELECT_ID_TYPE",
    UPLOAD_FRONT: "KYC_UPLOAD_FRONT",
    UPLOAD_BACK: "KYC_UPLOAD_BACK",
    UPLOAD_SELFIE: "KYC_UPLOAD_SELFIE",
    SAVE_NIN: "KYC_SAVE_NIN",
    SUBMIT: "KYC_SUBMIT",
    RETRY: "KYC_RETRY",
  },
};
