export const QUERY_KEYS = {
  CURRENCY: {
    SUPPORTED_CURRENCY: 'GET_SUPPORTED_CURRENCY',
  },
  CRYPTO: {
    SUPPORTED_CRYPTO: 'GET_SUPPORTED_CRYPTO',
    PLATFORM_CRYPTO_WALLET: 'GET_PLATFORM_CRYPTO_WALLET',
  },
  EXCHANGE_RATE: {
    GET_CRYPTO_TO_CURRENCY_EXCHANGE_RATE: 'GET_CRYPTO_TO_CURRENCY_EXCHANGE_RATE',
  },
  TRANSACTION: {
    GET_AMOUNT_TO_SEND: 'GET_AMOUNT_TO_SEND',
    INITIATE_TRANSACTION: 'INITIATE_TRANSACTION',
  },
  BANK: {
    PLATFORM_BANK_DETAILS: 'GET_PLATFORM_BANK_DETAILS',
  }
}