/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as TradeCryptoRouteImport } from './routes/trade-crypto'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ActivationResultRouteImport } from './routes/activation-result'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OauthSuccessRouteImport } from './routes/oauth/success'
import { Route as OauthErrorRouteImport } from './routes/oauth/error'
import { Route as DashboardTransactionsIdRouteImport } from './routes/dashboard/transactions/$id'

const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeCryptoRoute = TradeCryptoRouteImport.update({
  id: '/trade-crypto',
  path: '/trade-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationResultRoute = ActivationResultRouteImport.update({
  id: '/activation-result',
  path: '/activation-result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthErrorRoute = OauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsIdRoute = DashboardTransactionsIdRouteImport.update({
  id: '/dashboard/transactions/$id',
  path: '/dashboard/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation-result': typeof ActivationResultRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation-result': typeof ActivationResultRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation-result': typeof ActivationResultRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation-result'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/trade-crypto'
    | '/verify-account'
    | '/oauth/error'
    | '/oauth/success'
    | '/dashboard'
    | '/dashboard/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation-result'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/trade-crypto'
    | '/verify-account'
    | '/oauth/error'
    | '/oauth/success'
    | '/dashboard'
    | '/dashboard/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/activation-result'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/trade-crypto'
    | '/verify-account'
    | '/oauth/error'
    | '/oauth/success'
    | '/dashboard/'
    | '/dashboard/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationResultRoute: typeof ActivationResultRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TradeCryptoRoute: typeof TradeCryptoRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  OauthErrorRoute: typeof OauthErrorRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTransactionsIdRoute: typeof DashboardTransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-crypto': {
      id: '/trade-crypto'
      path: '/trade-crypto'
      fullPath: '/trade-crypto'
      preLoaderRoute: typeof TradeCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-result': {
      id: '/activation-result'
      path: '/activation-result'
      fullPath: '/activation-result'
      preLoaderRoute: typeof ActivationResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/error': {
      id: '/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof OauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions/$id': {
      id: '/dashboard/transactions/$id'
      path: '/dashboard/transactions/$id'
      fullPath: '/dashboard/transactions/$id'
      preLoaderRoute: typeof DashboardTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationResultRoute: ActivationResultRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TradeCryptoRoute: TradeCryptoRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  OauthErrorRoute: OauthErrorRoute,
  OauthSuccessRoute: OauthSuccessRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTransactionsIdRoute: DashboardTransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
