/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as TradeCryptoRouteImport } from './routes/trade-crypto'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SecurityPolicyRouteImport } from './routes/security-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AmlPolicyRouteImport } from './routes/aml-policy'
import { Route as ActivationResultRouteImport } from './routes/activation-result'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignInVerifyRouteImport } from './routes/sign-in/verify'
import { Route as OauthSuccessRouteImport } from './routes/oauth/success'
import { Route as OauthErrorRouteImport } from './routes/oauth/error'
import { Route as DisputeIdRouteImport } from './routes/dispute/$id'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardTransactionsIdRouteImport } from './routes/dashboard/transactions/$id'

const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeCryptoRoute = TradeCryptoRouteImport.update({
  id: '/trade-crypto',
  path: '/trade-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPolicyRoute = SecurityPolicyRouteImport.update({
  id: '/security-policy',
  path: '/security-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlPolicyRoute = AmlPolicyRouteImport.update({
  id: '/aml-policy',
  path: '/aml-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationResultRoute = ActivationResultRouteImport.update({
  id: '/activation-result',
  path: '/activation-result',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInVerifyRoute = SignInVerifyRouteImport.update({
  id: '/sign-in/verify',
  path: '/sign-in/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth/success',
  path: '/oauth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthErrorRoute = OauthErrorRouteImport.update({
  id: '/oauth/error',
  path: '/oauth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeIdRoute = DisputeIdRouteImport.update({
  id: '/dispute/$id',
  path: '/dispute/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsIdRoute = DashboardTransactionsIdRouteImport.update({
  id: '/dashboard/transactions/$id',
  path: '/dashboard/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activation-result': typeof ActivationResultRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dispute/$id': typeof DisputeIdRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activation-result': typeof ActivationResultRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dispute/$id': typeof DisputeIdRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activation-result': typeof ActivationResultRoute
  '/aml-policy': typeof AmlPolicyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rates': typeof RatesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security-policy': typeof SecurityPolicyRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/trade-crypto': typeof TradeCryptoRoute
  '/verify-account': typeof VerifyAccountRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dispute/$id': typeof DisputeIdRoute
  '/oauth/error': typeof OauthErrorRoute
  '/oauth/success': typeof OauthSuccessRoute
  '/sign-in/verify': typeof SignInVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/dashboard/transactions/$id': typeof DashboardTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activation-result'
    | '/aml-policy'
    | '/contact'
    | '/forgot-password'
    | '/privacy-policy'
    | '/rates'
    | '/reset-password'
    | '/security-policy'
    | '/sign-up'
    | '/terms-of-service'
    | '/trade-crypto'
    | '/verify-account'
    | '/dashboard/profile'
    | '/dispute/$id'
    | '/oauth/error'
    | '/oauth/success'
    | '/sign-in/verify'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activation-result'
    | '/aml-policy'
    | '/contact'
    | '/forgot-password'
    | '/privacy-policy'
    | '/rates'
    | '/reset-password'
    | '/security-policy'
    | '/sign-up'
    | '/terms-of-service'
    | '/trade-crypto'
    | '/verify-account'
    | '/dashboard/profile'
    | '/dispute/$id'
    | '/oauth/error'
    | '/oauth/success'
    | '/sign-in/verify'
    | '/dashboard'
    | '/sign-in'
    | '/dashboard/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activation-result'
    | '/aml-policy'
    | '/contact'
    | '/forgot-password'
    | '/privacy-policy'
    | '/rates'
    | '/reset-password'
    | '/security-policy'
    | '/sign-up'
    | '/terms-of-service'
    | '/trade-crypto'
    | '/verify-account'
    | '/dashboard/profile'
    | '/dispute/$id'
    | '/oauth/error'
    | '/oauth/success'
    | '/sign-in/verify'
    | '/dashboard/'
    | '/sign-in/'
    | '/dashboard/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivationResultRoute: typeof ActivationResultRoute
  AmlPolicyRoute: typeof AmlPolicyRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RatesRoute: typeof RatesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityPolicyRoute: typeof SecurityPolicyRoute
  SignUpRoute: typeof SignUpRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TradeCryptoRoute: typeof TradeCryptoRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DisputeIdRoute: typeof DisputeIdRoute
  OauthErrorRoute: typeof OauthErrorRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
  SignInVerifyRoute: typeof SignInVerifyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  DashboardTransactionsIdRoute: typeof DashboardTransactionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-crypto': {
      id: '/trade-crypto'
      path: '/trade-crypto'
      fullPath: '/trade-crypto'
      preLoaderRoute: typeof TradeCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-policy': {
      id: '/security-policy'
      path: '/security-policy'
      fullPath: '/security-policy'
      preLoaderRoute: typeof SecurityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml-policy': {
      id: '/aml-policy'
      path: '/aml-policy'
      fullPath: '/aml-policy'
      preLoaderRoute: typeof AmlPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation-result': {
      id: '/activation-result'
      path: '/activation-result'
      fullPath: '/activation-result'
      preLoaderRoute: typeof ActivationResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/verify': {
      id: '/sign-in/verify'
      path: '/sign-in/verify'
      fullPath: '/sign-in/verify'
      preLoaderRoute: typeof SignInVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/success': {
      id: '/oauth/success'
      path: '/oauth/success'
      fullPath: '/oauth/success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/error': {
      id: '/oauth/error'
      path: '/oauth/error'
      fullPath: '/oauth/error'
      preLoaderRoute: typeof OauthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute/$id': {
      id: '/dispute/$id'
      path: '/dispute/$id'
      fullPath: '/dispute/$id'
      preLoaderRoute: typeof DisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions/$id': {
      id: '/dashboard/transactions/$id'
      path: '/dashboard/transactions/$id'
      fullPath: '/dashboard/transactions/$id'
      preLoaderRoute: typeof DashboardTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivationResultRoute: ActivationResultRoute,
  AmlPolicyRoute: AmlPolicyRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RatesRoute: RatesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityPolicyRoute: SecurityPolicyRoute,
  SignUpRoute: SignUpRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TradeCryptoRoute: TradeCryptoRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DisputeIdRoute: DisputeIdRoute,
  OauthErrorRoute: OauthErrorRoute,
  OauthSuccessRoute: OauthSuccessRoute,
  SignInVerifyRoute: SignInVerifyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  DashboardTransactionsIdRoute: DashboardTransactionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
